apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cartyx-realtime.fullname" . }}
  labels:
    {{- include "cartyx-realtime.labels" . | nindent 4 }}
type: Opaque
stringData:
  sessionSecret: {{ .Values.secret.sessionSecret | quote }}
  mongodbUri: {{ .Values.secret.mongodbUri | quote }}
