apiVersion: v1
kind: Service
metadata:
  name: {{ include "cartyx-realtime.fullname" . }}
  labels:
    {{- include "cartyx-realtime.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "cartyx-realtime.selectorLabels" . | nindent 4 }}
  ports:
    - name: ws
      port: {{ .Values.service.port }}
      targetPort: ws
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
